import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {SPACE_PLATES,nebulaPlate,stationPlateRole,stationPlateAlpha,spaceParallax,sunScreen,sunInView,nearestStation,SPACE_DRIFT,stationSpinAngle,stationOrthoSize,STATION_ORTHO,stationPlateBox,coverAnchor,stationWorldSize} from '../dist/space-sky.mjs';

assert.equal(SPACE_PLATES.length,11);
assert.equal(nebulaPlate('nebula'),'nebula_soft_a');
assert.equal(nebulaPlate('dust'),'nebula_soft_a');
assert.equal(nebulaPlate('clear'),'nebula_soft_b');
assert.equal(nebulaPlate('deep'),'nebula_soft_b');
assert.equal(stationPlateRole(120),'station_exterior','no hangar plate swap in flight');
assert.equal(stationPlateRole(200),'station_exterior');
assert.equal(stationPlateRole(500),'station_exterior');
assert.equal(stationPlateRole(1600),'station_approach');
assert.equal(stationPlateRole(4000),null);
assert.equal(stationPlateAlpha(600,'station_exterior'),1,'station hull is opaque');
assert.equal(stationPlateAlpha(1600,'station_approach'),1,'approach hull is opaque once in range');
assert.ok(stationPlateAlpha(2390,'station_approach')>=.28&&stationPlateAlpha(2390,'station_approach')<1,'far edge fades in');
const slow=spaceParallax(1000,0,'far',800);
const fast=spaceParallax(1000,0,'dust',800);
assert.ok(Math.abs(fast.x)>Math.abs(slow.x),'dust drifts faster than the far field');
assert.ok(SPACE_DRIFT.far<SPACE_DRIFT.nebula&&SPACE_DRIFT.nebula<SPACE_DRIFT.mid&&SPACE_DRIFT.mid<SPACE_DRIFT.dust);
const sun=sunScreen({x:100,y:50},0,0,200,100,1);
assert.deepEqual(sun,{x:200,y:100});
assert.equal(sunInView(sun,200,100,0),false);
assert.equal(sunInView({x:40,y:40},200,100,10),true);
const near=nearestStation([{type:'station',x:10,y:0,id:'a'},{type:'station',x:400,y:0,id:'b'},{type:'beacon',x:0,y:0}],{x:0,y:0});
assert.equal(near.station.id,'a');
assert.equal(near.dist,10);
const sw=readFileSync(new URL('../dist/sw.js',import.meta.url),'utf8');
assert.match(sw,/farbound-v3\.0\.0-space13/);
assert.equal(STATION_ORTHO,'station_ortho');
assert.equal(stationSpinAngle(0,false),0);
assert.ok(stationSpinAngle(2,false)>stationSpinAngle(2,true),'performance spin is slower');
assert.ok(stationSpinAngle(3,false)>stationSpinAngle(1,false));
assert.ok(stationOrthoSize('station_exterior',800,400)>stationOrthoSize('station_approach',800,400));
assert.equal(stationOrthoSize('station_exterior',390,844),stationOrthoSize('station_exterior',844,390));
assert.ok(Math.abs(stationWorldSize(65,.75)-stationWorldSize(65,1)*.75)<1e-9,'station scales with zoom like ships');
assert.ok(stationWorldSize(48,1)<stationWorldSize(65,1));
const skySrc=readFileSync(new URL('../dist/space-sky.mjs',import.meta.url),'utf8');
assert.match(skySrc,/ctx\.rotate\(/);
assert.match(skySrc,/station_ortho/);
assert.ok(!/STATION_ROT\[/.test(skySrc),'exterior station is not a plate-swap cycle');
assert.ok(!/spin\.fade/.test(skySrc),'rot frames are not crossfaded into a second silhouette');
assert.ok(!/lights_bay_idle/.test(skySrc),'ortho hull does not take the old light overlays');
const phone=stationPlateBox('dock_bay',390,844);
assert.ok(phone.cover&&phone.dw>=390&&phone.dh>=844,'hangar covers a tall phone');
const wide=stationPlateBox('dock_bay',844,390);
assert.ok(wide.dw>=844&&wide.dh>=390,'hangar covers a wide phone');
const pinned=coverAnchor(40,20,phone.dw,phone.dh,390,844);
assert.ok(pinned.x-phone.dw/2<=0&&pinned.x+phone.dw/2>=390,'cover plate cannot slide a side gutter into view');
assert.ok(pinned.y-phone.dh/2<=0&&pinned.y+phone.dh/2>=844);
assert.equal(stationPlateBox('station_exterior',390,844).cover,false);
assert.match(sw,/space-sky\.mjs/);
for(const name of SPACE_PLATES)assert.match(sw,new RegExp('assets/space/'+name+'\\.png'));
assert.match(sw,/assets\/space\/station_spin\/station_ortho\.png/);
assert.match(sw,/assets\/space\/station_spin\/station_ortho_b\.png/);
console.log('PASS Space plates pick nebula, station role, and parallax order');
