import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {SPACE_PLATES,nebulaPlate,stationPlateRole,stationPlateAlpha,spaceParallax,sunScreen,sunInView,nearestStation,SPACE_DRIFT,stationRotFrame,stationLightPhase,STATION_ROT,STATION_LIGHT_SKIP} from '../dist/space-sky.mjs';

assert.equal(SPACE_PLATES.length,11);
assert.equal(nebulaPlate('nebula'),'nebula_soft_a');
assert.equal(nebulaPlate('dust'),'nebula_soft_a');
assert.equal(nebulaPlate('clear'),'nebula_soft_b');
assert.equal(nebulaPlate('deep'),'nebula_soft_b');
assert.equal(stationPlateRole(120),'dock_bay');
assert.equal(stationPlateRole(200),'dock_bay');
assert.equal(stationPlateRole(500),'station_exterior');
assert.equal(stationPlateRole(1600),'station_approach');
assert.equal(stationPlateRole(4000),null);
assert.ok(stationPlateAlpha(100,'dock_bay')>stationPlateAlpha(2000,'station_approach'));
assert.ok(stationPlateAlpha(2000,'station_approach')>=.28);
const slow=spaceParallax(1000,0,'far',800);
const fast=spaceParallax(1000,0,'dust',800);
assert.ok(Math.abs(fast.x)>Math.abs(slow.x),'dust drifts faster than the far field');
assert.ok(SPACE_DRIFT.far<SPACE_DRIFT.nebula&&SPACE_DRIFT.nebula<SPACE_DRIFT.mid&&SPACE_DRIFT.mid<SPACE_DRIFT.dust);
const sun=sunScreen({x:100,y:50},0,0,200,100,1);
assert.deepEqual(sun,{x:200,y:100});
assert.equal(sunInView(sun,200,100,0),false);
assert.equal(sunInView({x:40,y:40},200,100,10),true);
const near=nearestStation([{type:'station',x:10,y:0,id:'a'},{type:'station',x:400,y:0,id:'b'},{type:'beacon',x:0,y:0}],{x:0,y:0});
assert.equal(near.station.id,'a');
assert.equal(near.dist,10);
const sw=readFileSync(new URL('../dist/sw.js',import.meta.url),'utf8');
assert.match(sw,/farbound-v3\.0\.0-space6/);
assert.equal(STATION_ROT.length,8);
const rot=stationRotFrame(0.8,false);
assert.equal(rot.index,1);
assert.equal(rot.next,2);
assert.equal(stationRotFrame(0,false).index,0);
assert.ok(stationRotFrame(2,true).index<stationRotFrame(2,false).index,'performance spin is slower');
const lights=stationLightPhase(0,false);
assert.equal(lights.beacon,'lights_beacon_a');
assert.equal(stationLightPhase(.9,false).beacon,null);
assert.equal(stationLightPhase(0,true).beacon,null);
for(const name of STATION_LIGHT_SKIP)assert.ok(name!==lights.beacon,'dense station plates are not light masks');
const skySrc=readFileSync(new URL('../dist/space-sky.mjs',import.meta.url),'utf8');
assert.ok(!/spin\.fade/.test(skySrc),'rot frames are not crossfaded into a second silhouette');
assert.match(sw,/space-sky\.mjs/);
for(const name of SPACE_PLATES)assert.match(sw,new RegExp('assets/space/'+name+'\\.png'));
console.log('PASS Space plates pick nebula, station role, and parallax order');
